### ISSUE TITLE
在执行langchain的示例代码时发生报错

### ISSUE THREAD

**Issue by HJH0924** [xing61/xiaoyi-robot#15]
我执行[文档](https://github.com/xing61/xiaoyi-robot/blob/main/%E5%9C%BA%E6%99%AF%E7%A4%BA%E4%BE%8B/langchain%E7%9A%84%E6%94%AF%E6%8C%81.md)中所给的代码：
import os
import requests
import time
import json
import time
from langchain.llms import OpenAI

API_SECRET_KEY = "sk-zk28291xxxxx"; # 这里我进行了隐藏，但是运行的时候我替换成了我的key
BASE_URL = "https://flag.smarttrot.com/v1"; #智增增的base-url

os.environ["OPENAI_API_KEY"] = API_SECRET_KEY
os.environ["OPENAI_API_BASE"] = BASE_URL

def text():
    llm = OpenAI(temperature=0.9,model='gpt-3.5-turbo-instruct')
    text = "What would be a good company name for a company that makes colorful socks?"
    print(llm(text))

if __name__ == '__main__':
    text();

报错信息：
/usr/bin/python3.10 /home/bigmath/hjh/llm/langchain_test.py 
Traceback (most recent call last):
  File "/home/bigmath/hjh/llm/langchain_test.py", line 29, in <module>
    text();
  File "/home/bigmath/hjh/llm/langchain_test.py", line 25, in text
    print(llm(text))
  File "/usr/local/lib/python3.10/dist-packages/langchain/llms/base.py", line 825, in __call__
    self.generate(
  File "/usr/local/lib/python3.10/dist-packages/langchain/llms/base.py", line 621, in generate
    output = self._generate_helper(
  File "/usr/local/lib/python3.10/dist-packages/langchain/llms/base.py", line 523, in _generate_helper
    raise e
  File "/usr/local/lib/python3.10/dist-packages/langchain/llms/base.py", line 510, in _generate_helper
    self._generate(
  File "/usr/local/lib/python3.10/dist-packages/langchain/llms/openai.py", line 385, in _generate
    response = completion_with_retry(
  File "/usr/local/lib/python3.10/dist-packages/langchain/llms/openai.py", line 109, in completion_with_retry
    retry_decorator = _create_retry_decorator(llm, run_manager=run_manager)
  File "/usr/local/lib/python3.10/dist-packages/langchain/llms/openai.py", line 92, in _create_retry_decorator
    openai.error.Timeout,
AttributeError: module 'openai' has no attribute 'error'

Process finished with exit code 1

**Comment by xing61** [comment]
pip list看下openai包的版本号呢？

**Comment by HJH0924** [comment]
![image](https://github.com/xing61/xiaoyi-robot/assets/73840153/d5c03b0d-810d-44f4-9425-70334a03a025)
![image](https://github.com/xing61/xiaoyi-robot/assets/73840153/700e2927-69bc-41e5-b69b-c37700b78f32)
openai，langchain的版本如图↑
